# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_valid_index": "00_core.ipynb",
         "normalize_funcs_image_tab": "00_core.ipynb",
         "ImageTabDataset": "01_dataset.ipynb",
         "get_imagetabdatasets": "01_dataset.ipynb",
         "CNNTabularModel": "02_model.ipynb",
         "auc_roc_score": "03_metric.ipynb",
         "ROCAUC": "03_metric.ipynb"}

modules = ["core.py",
           "dataset.py",
           "model.py",
           "metric.py"]

doc_url = "https://naity.github.io/image_tabular/"

git_url = "https://github.com/naity/image_tabular/tree/master/"

def custom_doc_links(name): return None
